#!/usr/bin/env bash


##########################################
#
# Description : deploy docker containers on-the-fly
#
# Author : Mondher
#
# Date : 01/01/2025
#
#########################################

# Choose Options:
case "$1" in
	--create)
		nb_containers=1
		[ "$2" != "" ] && nb_containers=$2
		for i in $(seq 1 $nb_containers); do
		    docker run -itd --name $USER-alpine-$i alpine:latest
		    echo "Container $USER-alpine-$i created !"
		done
		;;
	
	--drop)
		echo "Start containers suppression"
		docker rm -f $(docker ps | grep $USER-alpine | awk '{print $1}')
		echo "Suppression finished"
		;;
	--info)
		echo ""
		echo "--info was chosen !"
		echo""
		;;
	
	--start)
		echo ""
		echo "--start was chosen !"
		echo""
		;;
	
	--ansible)
		echo ""
		echo "--ansible was chosen !"
		echo""
		;;
	*)
		echo "
		Options:

			- --create  : run containers
	
			- --drop    : delete containers
	
			- --info    : containers features (ip, name, user...)

			- --start   : restart containers

			- --ansible : deploy ansible tree
"
;;
esac
