#!/usr/bin/env bash


##########################################
#
# Description : deploy docker containers on-the-fly
#
# Author : Mondher
#
# Date : 01/01/2025
#
#########################################

# Choose Options:
case "$1" in
	--create)
		nb_containers=1
		[ "$2" != "" ] && nb_containers=$2
		
		#For correct ids even when containers already exist 
		min=1
		max=0

		idxMax=$(docker ps -a --format '{{.Names}}' | awk -F "-" -v user=$USER '$0 ~ user"-alpine" {print $3}' | sort -r | head -1)		
		
		min=$(($idxMax + $min))
		max=$(($idxMax + $nb_containers))

		for i in $(seq $min $max); do
		    docker run -itd --name $USER-alpine-$i alpine:latest
		    echo "Container $USER-alpine-$i created !"
		done
		;;
	
	--drop)
		echo "Start containers suppression"
		docker rm -f $(docker ps -a | grep $USER-alpine | awk '{print $1}')
		echo "Suppression finished"
		;;
	--info)
		for containerId in $(docker ps -a | grep $USER-alpine | awk '{print $1}'); do
		    docker inspect --format ' => {{.Name}} - {{.NetworkSettings.IPAddress}}' $containerId 
		done
		;;
	
	--start)
		docker start $(docker ps -a | grep $USER-alpine | awk '{print $1}')
		;;
	
	--ansible)
		echo ""
		echo "--ansible was chosen !"
		echo""
		;;
	*)
		echo "
		Options:

			- --create  : run containers
	
			- --drop    : delete containers
	
			- --info    : containers features (ip, name, user...)

			- --start   : restart containers

			- --ansible : deploy ansible tree
"
;;
esac
